-- ============================================================
-- 1. KHỞI TẠO DATABASE & XÓA CŨ (NẾU CÓ)
-- ============================================================
USE master;
GO

IF DB_ID('QL_THUVIEN') IS NOT NULL
BEGIN
    ALTER DATABASE QL_THUVIEN SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE QL_THUVIEN;
END
GO

CREATE DATABASE QL_THUVIEN;
GO
USE QL_THUVIEN;
GO

-- ============================================================
-- 2. TẠO BẢNG (TABLES) - CẤU TRÚC MỚI NHẤT
-- ============================================================

-- 2.1 Bảng Người Dùng
CREATE TABLE NGUOIDUNG (
    MANGUOIDUNG INT PRIMARY KEY IDENTITY(1,1),
    HOTEN NVARCHAR(100) NOT NULL,
    EMAIL NVARCHAR(100) UNIQUE,
    SDT NVARCHAR(20),
    MATKHAU NVARCHAR(255) NOT NULL, 
    VAITRO NVARCHAR(20) NOT NULL, 
    TRANGTHAI NVARCHAR(20) DEFAULT N'Active', 
    ANHDAIDIEN NVARCHAR(255) NULL, 
    NGAYTAO DATETIME DEFAULT GETDATE()
);
GO

-- 2.2 Bảng Độc Giả
CREATE TABLE DOCGIA (
    MADOCGIA INT PRIMARY KEY IDENTITY(1,1),
    MANGUOIDUNG INT UNIQUE,
    TINHTRANGTHE NVARCHAR(20) DEFAULT N'Active',
    NGAYCAP DATE DEFAULT GETDATE(),
    NGAYHETHAN DATE,
    FOREIGN KEY (MANGUOIDUNG) REFERENCES NGUOIDUNG(MANGUOIDUNG)
);
GO

-- 2.3 Bảng Nhân Viên
CREATE TABLE NHANVIEN (
    MANHANVIEN INT PRIMARY KEY IDENTITY(1,1),
    MANGUOIDUNG INT UNIQUE,
    CHUCVU NVARCHAR(50),
    NGAYVAOLAM DATE DEFAULT GETDATE(),
    FOREIGN KEY (MANGUOIDUNG) REFERENCES NGUOIDUNG(MANGUOIDUNG)
);
GO

-- 2.4 Bảng Sách
CREATE TABLE SACH (
    MASACH INT PRIMARY KEY IDENTITY(1,1),
    TENSACH NVARCHAR(200) NOT NULL,
    TACGIA NVARCHAR(100),
    THELOAI NVARCHAR(100),
    NHAXUATBAN NVARCHAR(100),
    NAMXUATBAN INT,
    SOLUONG INT DEFAULT 0,
    VITRISACH NVARCHAR(50),
    ANHBIA NVARCHAR(255),
    MAQR NVARCHAR(100) NULL,
    MOTA NVARCHAR(MAX) NULL,
    TRANGTHAI NVARCHAR(20) DEFAULT N'Có sẵn'
);
GO

-- 2.5 Bảng Phiếu Mượn (Đã thêm TIENMUON, TONGTIEN)
CREATE TABLE PHIEUMUON (
    MAPHIEUMUON INT PRIMARY KEY IDENTITY(1,1),
    MADOCGIA INT,
    MASACH INT,
    MANHANVIEN INT NULL,
    NGAYMUON DATE DEFAULT GETDATE(),
    HANTRA DATE,
    NGAYTRA DATE NULL,
    TRANGTHAI NVARCHAR(20) DEFAULT N'Đang mượn', 
    SOTIENPHAT DECIMAL(10,2) DEFAULT 0,
    
    -- MỚI: Thêm trực tiếp tại đây, không cần ALTER sau này
    TIENMUON DECIMAL(10,2) NOT NULL DEFAULT 0,
    TONGTIEN DECIMAL(10,2) NOT NULL DEFAULT 0,

    FOREIGN KEY (MADOCGIA) REFERENCES DOCGIA(MADOCGIA),
    FOREIGN KEY (MASACH) REFERENCES SACH(MASACH),
    FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN)
);
GO

-- 2.6 Tiền Phạt
CREATE TABLE PHAT (
    MAPHAT INT PRIMARY KEY IDENTITY(1,1),
    MAPHIEUMUON INT,
    SOTIEN DECIMAL(10,2),
    LYDO NVARCHAR(255),
    DATHANHTOAN BIT DEFAULT 0,
    NGAYPHAT DATE DEFAULT GETDATE(),
    FOREIGN KEY (MAPHIEUMUON) REFERENCES PHIEUMUON(MAPHIEUMUON)
);
GO

-- 2.7 Yêu Cầu Mượn
CREATE TABLE YEUCAUMUON (
    MAYEUCAU INT PRIMARY KEY IDENTITY(1,1),
    MADOCGIA INT,
    MASACH INT,
    NGAYYEUCAU DATETIME DEFAULT GETDATE(),
    TRANGTHAI NVARCHAR(20) DEFAULT N'Chờ duyệt',
    FOREIGN KEY (MADOCGIA) REFERENCES DOCGIA(MADOCGIA),
    FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
);
GO

-- 2.8 Các bảng Log và Tham số
CREATE TABLE THONGBAO (
    MATHONGBAO INT PRIMARY KEY IDENTITY(1,1),
    MANGUOIDUNG INT,
    TIEUDE NVARCHAR(200),
    NOIDUNG NVARCHAR(MAX),
    NGAYGUI DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (MANGUOIDUNG) REFERENCES NGUOIDUNG(MANGUOIDUNG)
);

CREATE TABLE LOGIN_LOG (
    ID INT PRIMARY KEY IDENTITY(1,1),
    MANGUOIDUNG INT,
    THOIGIAN DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (MANGUOIDUNG) REFERENCES NGUOIDUNG(MANGUOIDUNG)
);

-- Bảng Hoạt Động Log (Đã thêm DOITUONG, NOIDUNG)
CREATE TABLE HOATDONG_LOG (
    ID INT PRIMARY KEY IDENTITY(1,1),
    MANGUOIDUNG INT,
    HANHDONG NVARCHAR(200),
    THOIGIAN DATETIME DEFAULT GETDATE(),
    
    -- MỚI: Thêm trực tiếp
    DOITUONG NVARCHAR(200) NULL,
    NOIDUNG NVARCHAR(MAX) NULL,

    FOREIGN KEY (MANGUOIDUNG) REFERENCES NGUOIDUNG(MANGUOIDUNG)
);

CREATE TABLE THAMSO (
    TENTHAMSO NVARCHAR(50) PRIMARY KEY,
    GIATRI NVARCHAR(255) NOT NULL,
    MOTA NVARCHAR(255)
);

-- Các bảng danh mục
CREATE TABLE THELOAI (MA INT IDENTITY(1,1) PRIMARY KEY, TEN NVARCHAR(100));
CREATE TABLE TACGIA (MA INT IDENTITY(1,1) PRIMARY KEY, TEN NVARCHAR(100));
CREATE TABLE NHAXUATBAN (MA INT IDENTITY(1,1) PRIMARY KEY, TEN NVARCHAR(100), DIACHI NVARCHAR(200), SDT NVARCHAR(20));
GO

-- ============================================================
-- 3. STORED PROCEDURE
-- ============================================================
CREATE PROCEDURE sp_MuonSach
    @MaDocGia INT,
    @MaSach INT,
    @MaNhanVien INT,
    @NgayMuon DATE,
    @HanTra DATE
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRANSACTION;
    BEGIN TRY
        DECLARE @SoLuong INT;
        SELECT @SoLuong = SOLUONG FROM SACH WHERE MASACH = @MaSach;

        IF @SoLuong <= 0
        BEGIN
            ROLLBACK TRANSACTION;
            THROW 51000, N'Sách này đã hết, không thể mượn!', 1;
            RETURN;
        END

        INSERT INTO PHIEUMUON (MADOCGIA, MASACH, MANHANVIEN, NGAYMUON, HANTRA, TRANGTHAI)
        VALUES (@MaDocGia, @MaSach, @MaNhanVien, @NgayMuon, @HanTra, N'Đang mượn');

        UPDATE SACH SET SOLUONG = SOLUONG - 1 WHERE MASACH = @MaSach;
        UPDATE SACH SET TRANGTHAI = N'Hết hàng' WHERE MASACH = @MaSach AND SOLUONG = 0;

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO

-- ============================================================
-- 4. INSERT DỮ LIỆU MẪU
-- ============================================================
-- 4.0 Thêm Tham Số (Đã gộp đủ 3 tham số)
INSERT INTO THAMSO (TENTHAMSO, GIATRI, MOTA) VALUES (N'TIEN_PHAT_MOI_NGAY', N'5000', N'Số tiền phạt trễ hạn 1 ngày');
INSERT INTO THAMSO (TENTHAMSO, GIATRI, MOTA) VALUES (N'SO_NGAY_GIA_HAN', N'7', N'Số ngày được cộng thêm khi gia hạn');
INSERT INTO THAMSO (TENTHAMSO, GIATRI, MOTA) VALUES (N'SO_TIEN_MUON_MOI_NGAY', N'5000', N'Số tiền mượn trên mỗi ngày'); 

-- 4.1 Danh mục
INSERT INTO THELOAI (TEN) VALUES (N'Công nghệ'), (N'Văn học'), (N'Kinh tế');
INSERT INTO TACGIA (TEN) VALUES (N'Nguyễn Nhật Ánh'), (N'J.K. Rowling');
INSERT INTO NHAXUATBAN (TEN) VALUES (N'NXB Trẻ'), (N'NXB Kim Đồng');

-- 4.2 Người dùng & Nhân viên
INSERT INTO NGUOIDUNG (HOTEN, EMAIL, SDT, MATKHAU, VAITRO) VALUES (N'Administrator', 'admin@library.com', '0900000001', 'E10ADC3949BA59ABBE56E057F20F883E', 'admin');
INSERT INTO NHANVIEN (MANGUOIDUNG, CHUCVU) VALUES (1, 'QuanLy');

INSERT INTO NGUOIDUNG (HOTEN, EMAIL, SDT, MATKHAU, VAITRO) VALUES (N'Trần Thu Thư', 'thuthu1@library.com', '0900000002', 'E10ADC3949BA59ABBE56E057F20F883E', 'nhanvien');
INSERT INTO NHANVIEN (MANGUOIDUNG, CHUCVU) VALUES (2, 'ThuThu');

-- 4.3 Độc giả
DECLARE @i INT = 1;
WHILE @i <= 20
BEGIN
    INSERT INTO NGUOIDUNG (HOTEN, EMAIL, SDT, MATKHAU, VAITRO)
    VALUES (N'Độc Giả ' + CAST(@i AS NVARCHAR), 'docgia' + CAST(@i AS NVARCHAR) + '@gmail.com', '098' + CAST(@i AS NVARCHAR), 'E10ADC3949BA59ABBE56E057F20F883E', 'DocGia');
    INSERT INTO DOCGIA (MANGUOIDUNG, NGAYHETHAN) VALUES (SCOPE_IDENTITY(), DATEADD(YEAR, 1, GETDATE()));
    SET @i = @i + 1;
END
GO

-- 4.4 Sách (Tạo 150 cuốn)
-- 20 cuốn đầu
INSERT INTO SACH (TENSACH, TACGIA, THELOAI, NHAXUATBAN, NAMXUATBAN, SOLUONG, VITRISACH, MOTA)
VALUES 
(N'Nhà Giả Kim', N'Paulo Coelho', N'Tiểu thuyết', N'NXB Văn Học', 2020, 10, N'Kệ A1', N'Cuốn sách bán chạy nhất.'),
(N'Đắc Nhân Tâm', N'Dale Carnegie', N'Kỹ năng', N'NXB Trẻ', 2019, 15, N'Kệ B2', N'Nghệ thuật thu phục lòng người.'),
(N'Clean Code', N'Robert C. Martin', N'Công nghệ', N'Prentice Hall', 2008, 5, N'Kệ C1', N'Viết code sạch.');

-- Vòng lặp tạo sách mẫu
DECLARE @j INT = 4;
WHILE @j <= 150
BEGIN
    INSERT INTO SACH (TENSACH, TACGIA, THELOAI, NHAXUATBAN, NAMXUATBAN, SOLUONG, VITRISACH, MOTA)
    VALUES (
        N'Sách tham khảo số ' + CAST(@j AS NVARCHAR),
        N'Tác giả AI',
        N'Khoa học',
        N'NXB Tổng hợp',
        2022, 10, N'Kho A', N'Mô tả sách...'
    );
    SET @j = @j + 1;
END
GO

-- 4.5 Phiếu Mượn (Dữ liệu mẫu - Đã có TIENMUON, TONGTIEN)
INSERT INTO PHIEUMUON (MADOCGIA, MASACH, MANHANVIEN, NGAYMUON, HANTRA, TRANGTHAI, TIENMUON, TONGTIEN)
VALUES 
(1, 1, 1, GETDATE(), DATEADD(DAY, 7, GETDATE()), N'Đang mượn', 35000, 35000),
(2, 2, 1, GETDATE(), DATEADD(DAY, 7, GETDATE()), N'Đang mượn', 35000, 35000),
(3, 3, 1, DATEADD(DAY, -10, GETDATE()), DATEADD(DAY, -3, GETDATE()), N'Đang mượn', 35000, 35000);

-- Một phiếu đã trả và bị phạt
INSERT INTO PHIEUMUON (MADOCGIA, MASACH, MANHANVIEN, NGAYMUON, HANTRA, NGAYTRA, TRANGTHAI, SOTIENPHAT, TIENMUON, TONGTIEN)
VALUES 
(1, 4, 1, DATEADD(DAY, -10, GETDATE()), DATEADD(DAY, -3, GETDATE()), GETDATE(), N'Đã trả', 15000, 35000, 50000); 

INSERT INTO PHAT (MAPHIEUMUON, SOTIEN, LYDO, DATHANHTOAN, NGAYPHAT)
VALUES (SCOPE_IDENTITY(), 15000, N'Quá hạn 3 ngày', 1, GETDATE());

PRINT N'Cài đặt Database QL_THUVIEN thành công!';
GO